version: "3.5"
  
services:
  sth_mongo:
    image: mongo:3.6
    container_name: sth_mongo
    hostname: sth_mongo
    expose:
      - "27017"
    volumes:
      - type: volume
        source: sth_mongo_db
        target: /data/db
        read_only: false
      - type: volume
        source: sth_mongo_configdb
        target: /data/configdb
        read_only: false
    networks:
      - sth_net
    restart: always

  sth:
    image: telefonicaiot/fiware-sth-comet:2.7.0
    container_name: sth
    hostname: sth
    ports:
      - "8666:8666"
      - "5050:5050"
    # expose:
    #   - "8666"
    depends_on:
      - sth_mongo
    networks:
      - sth_net
      - fiware_net
    restart: always
    environment:
      - STH_HOST=0.0.0.0
      - STH_PORT=8666
      - DATA_MODEL=collection-per-entity
      - DB_URI=sth_mongo:27017
      - SHOULD_STORE=both
      - TRUNCATION_SIZE=0
      - TRUNCATION_EXPIRE_AFTER_SECONDS=600
      - AGGREGATION_BY=['day', 'hour', 'minute']

volumes:
  sth_mongo_db:
  sth_mongo_configdb:

networks:
  sth_net:
    driver: bridge
  fiware_net:
    external: true
